name: Scheduled Task

on:
  schedule:
    # This will run the task every hour
    - cron: '0 * * * *'  
  workflow_dispatch:  # This allows you to trigger the job manually

jobs:
  trigger-vercel-function:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel endpoint
        run: |
          curl -X GET https://your-vercel-app.vercel.app/api/bot
